CMAKE_MINIMUM_REQUIRED(VERSION 2.8.12 FATAL_ERROR)

PROJECT(json11-download NONE)

INCLUDE(ExternalProject)
ExternalProject_Add(json11
	GIT_REPOSITORY https://github.com/dropbox/json11.git
	GIT_TAG master
	SOURCE_DIR "${CONFU_DEPENDENCIES_SOURCE_DIR}/json11"
	BINARY_DIR "${CONFU_DEPENDENCIES_BINARY_DIR}/json11"
	CONFIGURE_COMMAND ""
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
	TEST_COMMAND ""
)
